name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx_standard:
          - 'c++14'
          - 'c++17'
        cxx_compiler:
          - 'g++'
          - 'clang++'

    steps:
      - uses: actions/checkout@v1
      - run: make actions CXXSTD=${{ matrix.cxx_standard }} CXX=${{ matrix.cxx_compiler }}
      - run: ./test.exe
