name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx_standard:
          - 'c++14'
          - 'c++17'

    env:
        CXXSTD: ${{ matrix.cxx_standard }}

    steps:
      - uses: actions/checkout@v1
      - run: make
